cron-for-the-sales-data_Oleg-Vakheta
DocHQ/helpers pull request #1
Opened 2022-01-18 17:27 UTC by oleg-vakheta

helper to send emails

2022-01-18 17:27 UTC, oleg-vakheta commented
Task linked: [CU-1v2mmz2 cron for the sales data](https://app.clickup.com/t/1v2mmz2)

2022-01-18 17:53 UTC, Jammizzle requested changes

2022-01-18 17:53 UTC, Jammizzle commented on mail/sendmail.go
> +	sendgridClient = sendgrid.NewSendClient(os.Getenv("SENDGRID_API_KEY"))
no need for sentry to be called from the logging package,

2022-01-18 17:53 UTC, Jammizzle commented on mail/sendmail.go
> +		return fmt.Errorf("incorrect status code reurned %v", res.StatusCode)
we could instead return a better error then have the caller handle the logging/sentry

2022-01-19 10:26 UTC, Jammizzle approved these changes

2022-01-26 09:00 UTC, merged